# Generated by Django 4.2.4 on 2024-01-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('age', models.IntegerField(max_length=1)),
                ('monthly_salary', models.IntegerField(max_length=200)),
                ('approved_limit', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField(max_length=50)),
                ('tenure', models.IntegerField(max_length=50)),
                ('interest_rate', models.FloatField(max_length=50)),
                ('monthly_installment', models.FloatField(max_length=50)),
                ('emi_paid_on_time', models.IntegerField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditapi.customer')),
            ],
        ),
    ]
